In [ ]:
!pip install -r requirements.txt

In [ ]:
!python main-single.py --batch-size 600

In [ ]:
!python main-multi.py --batch-size 600 --cli-ite-num 3

tensor([[[[ 0.1031, -0.0883, -0.0388,  0.0939, -0.1883],
          [ 0.1199, -0.0411,  0.1017,  0.0278, -0.0245],
          [ 0.0555,  0.0099,  0.0730, -0.0779, -0.0146],
          [-0.0180,  0.0290, -0.0008,  0.1748,  0.0622],
          [-0.0745, -0.1208, -0.0335, -0.0863, -0.0641]]],


        [[[ 0.0096,  0.1192,  0.1087, -0.1955,  0.1240],
          [ 0.0559,  0.1897,  0.1320, -0.1822, -0.1902],
          [-0.0965,  0.1756, -0.0333,  0.0856, -0.0929],
          [ 0.1962, -0.0846,  0.1500,  0.0024, -0.1054],
          [ 0.1028, -0.1062,  0.0588, -0.0578, -0.0219]]],


        [[[-0.1923, -0.0954,  0.1085, -0.0486,  0.1992],
          [ 0.1603, -0.0094, -0.1335,  0.1218,  0.0621],
          [-0.1293,  0.1299,  0.1214,  0.1774, -0.1121],
          [-0.0329, -0.0039,  0.0292, -0.1518, -0.1419],
          [ 0.1088, -0.0469,  0.0977,  0.0114,  0.0657]]],


        [[[ 0.0440,  0.0727,  0.0991, -0.1852,  0.1007],
          [-0.1406, -0.1509,  0.0122, -0.0341,  0.1175],
          [-0.1158,

No model's revelence is higher than threshold.
Train Epoch: 1
tensor([[[[-4.0789e+02, -4.1797e+02, -4.2521e+02, -3.9974e+02, -3.1687e+02],
          [-4.7571e+02, -5.0175e+02, -5.1227e+02, -4.5950e+02, -3.7529e+02],
          [-4.7131e+02, -5.0424e+02, -5.1184e+02, -4.7087e+02, -4.1477e+02],
          [-3.8942e+02, -4.1202e+02, -4.3157e+02, -4.4420e+02, -4.0247e+02],
          [-2.9054e+02, -2.9546e+02, -3.2375e+02, -3.3947e+02, -3.2962e+02]]],


        [[[-1.4340e+03, -1.6711e+03, -1.5691e+03, -1.1947e+03, -9.9904e+02],
          [-1.6317e+03, -1.7975e+03, -1.5809e+03, -1.0820e+03, -7.9824e+02],
          [-1.5656e+03, -1.6667e+03, -1.3924e+03, -1.0490e+03, -7.6944e+02],
          [-1.4770e+03, -1.3805e+03, -1.2246e+03, -9.6819e+02, -7.5420e+02],
          [-1.2291e+03, -1.1050e+03, -1.0150e+03, -8.6822e+02, -7.6448e+02]]],


        [[[-3.2129e+02, -4.6746e+02, -7.1870e+02, -8.8532e+02, -9.4676e+02],
          [-4.8124e+02, -6.2492e+02, -8.0396e+02, -9.4055e+02, -8.7532e+02],
      

No model's revelence is higher than threshold.
Train Epoch: 1
tensor([[[[ 3.4348e+06,  3.4013e+06,  3.4013e+06,  3.4013e+06,  3.2822e+06],
          [ 3.4013e+06,  3.4013e+06,  3.4013e+06,  3.4013e+06,  3.4012e+06],
          [ 3.4013e+06,  3.4013e+06,  3.4013e+06,  3.4013e+06,  3.4013e+06],
          [ 3.4013e+06,  3.4013e+06,  3.4013e+06,  3.4013e+06,  3.4026e+06],
          [ 3.3943e+06,  3.4012e+06,  3.4013e+06,  3.4013e+06,  3.3016e+06]]],


        [[[ 1.0189e+07,  1.0229e+07,  1.0229e+07,  1.0229e+07,  9.6789e+06],
          [ 1.0229e+07,  1.0229e+07,  1.0229e+07,  1.0229e+07,  1.0424e+07],
          [ 1.0229e+07,  1.0229e+07,  1.0229e+07,  1.0229e+07,  1.0406e+07],
          [ 1.0229e+07,  1.0229e+07,  1.0229e+07,  1.0229e+07,  1.0350e+07],
          [ 1.0223e+07,  1.0229e+07,  1.0229e+07,  1.0229e+07,  9.3183e+06]]],


        [[[ 5.6200e+06,  5.2690e+06,  5.2690e+06,  5.2690e+06,  5.1545e+06],
          [ 5.2679e+06,  5.2690e+06,  5.2690e+06,  5.2690e+06,  5.2690e+06],
      

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 2.8607e-01,
         9.7924e-02],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.5545e-05, 1.4169e-01,
         2.1455e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 7.0419e-04, 6.5968e-02,
         1.0888e-01],
        ...,
        [0.0000e+00, 0.0000e+00, 5.7528e-06,  ..., 0.0000e+00, 1.5123e-02,
         9.9816e-02],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 1.5725e-01,
         6.0092e-02],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 9.6714e-03,
         4.8998e-01]])
tensor([ 0.0036,  0.0096,  0.0042, -0.0335,  0.0028, -0.0005,  0.0035,  0.0047,
         0.0026,  0.0031])
Train Epoch: 1
No model's revelence is higher than threshold.
Train Epoch: 1
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0

No model's revelence is higher than threshold.
Train Epoch: 1
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0.,

No model's revelence is higher than threshold.
Train Epoch: 1

Test set: Average loss: 2.3025, Accuracy: 1135/10000 (11%)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0.

        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([ 1.7183e-08,  4.4809e-03, -1.7364e-04,  5.4169e-04, -6.6462e-04,


In [6]:
a = (1,2,3)
print(*a)

1 2 3


In [ ]:
import torch
a = torch.randn(10)
b = torch.randn(10)
print(a + b)


In [ ]:
c = a * b
print(c)
c[c < 0] = 0
print(c)
print(sum(c) / c.numel())

In [ ]:
import torch
a = torch.randn(10, 10)
print(a)
b= sum(sum(a))
print(b < 1)
print(torch.sum(a))

In [ ]:
a = [1,2,3]
b = [4,5,6]

for x in a:
    for y in b:
        break
    print(x, y)