In [2]:
!pip install -r requirements.txt

You should consider upgrading via the 'pip install --upgrade pip' command.


In [12]:
!python main-single.py --batch-size 600

^C
Traceback (most recent call last):
  File "main-single.py", line 8, in <module>
    from torchvision import datasets, transforms
  File "/Users/HypertasyZOY/anaconda3/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/Users/HypertasyZOY/anaconda3/lib/python3.6/site-packages/torchvision/models/__init__.py", line 1, in <module>
    from .alexnet import *
  File "/Users/HypertasyZOY/anaconda3/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 2, in <module>
    import torch.utils.model_zoo as model_zoo
  File "/Users/HypertasyZOY/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 12, in <module>
    from requests.utils import urlparse
  File "/Users/HypertasyZOY/anaconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/Users/HypertasyZOY/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 48,

In [ ]:
!python main-multi.py --batch-size 2000

tensor([[[[ 0.1031, -0.0883, -0.0388,  0.0939, -0.1883],
          [ 0.1199, -0.0411,  0.1017,  0.0278, -0.0245],
          [ 0.0555,  0.0099,  0.0730, -0.0779, -0.0146],
          [-0.0180,  0.0290, -0.0008,  0.1748,  0.0622],
          [-0.0745, -0.1208, -0.0335, -0.0863, -0.0641]]],


        [[[ 0.0096,  0.1192,  0.1087, -0.1955,  0.1240],
          [ 0.0559,  0.1897,  0.1320, -0.1822, -0.1902],
          [-0.0965,  0.1756, -0.0333,  0.0856, -0.0929],
          [ 0.1962, -0.0846,  0.1500,  0.0024, -0.1054],
          [ 0.1028, -0.1062,  0.0588, -0.0578, -0.0219]]],


        [[[-0.1923, -0.0954,  0.1085, -0.0486,  0.1992],
          [ 0.1603, -0.0094, -0.1335,  0.1218,  0.0621],
          [-0.1293,  0.1299,  0.1214,  0.1774, -0.1121],
          [-0.0329, -0.0039,  0.0292, -0.1518, -0.1419],
          [ 0.1088, -0.0469,  0.0977,  0.0114,  0.0657]]],


        [[[ 0.0440,  0.0727,  0.0991, -0.1852,  0.1007],
          [-0.1406, -0.1509,  0.0122, -0.0341,  0.1175],
          [-0.1158,

tensor([[[[-3.8529e+01, -4.3657e+01, -5.0690e+01, -5.2983e+01, -4.6269e+01],
          [-4.1991e+01, -4.8533e+01, -5.5171e+01, -5.4107e+01, -4.7035e+01],
          [-4.3965e+01, -5.1709e+01, -5.6051e+01, -5.4221e+01, -4.5480e+01],
          [-4.4051e+01, -5.0636e+01, -5.3871e+01, -5.1418e+01, -4.1412e+01],
          [-4.2132e+01, -4.6196e+01, -4.8770e+01, -4.4636e+01, -3.6035e+01]]],


        [[[-1.0411e+02, -1.2990e+02, -1.3869e+02, -1.2648e+02, -1.1158e+02],
          [-1.2237e+02, -1.4458e+02, -1.4142e+02, -1.1944e+02, -9.6812e+01],
          [-1.2647e+02, -1.4104e+02, -1.3168e+02, -1.0965e+02, -8.7927e+01],
          [-1.2755e+02, -1.2917e+02, -1.1749e+02, -9.7778e+01, -8.2562e+01],
          [-1.1842e+02, -1.1040e+02, -9.9718e+01, -8.5398e+01, -7.7337e+01]]],


        [[[-5.6824e+01, -6.8042e+01, -8.2518e+01, -9.7679e+01, -1.1523e+02],
          [-6.7803e+01, -7.9811e+01, -9.5177e+01, -1.0627e+02, -1.1831e+02],
          [-6.5819e+01, -8.3439e+01, -9.7230e+01, -1.0212e+02, -1.06

tensor([[[[-4.0160e+17, -1.2777e+18, -2.1015e+18, -2.2980e+18, -1.8661e+18],
          [-6.1512e+17, -1.6932e+18, -2.4207e+18, -2.4902e+18, -1.8208e+18],
          [-9.0612e+17, -2.0266e+18, -2.5919e+18, -2.5351e+18, -1.5786e+18],
          [-1.2980e+18, -2.1900e+18, -2.6846e+18, -2.3595e+18, -1.2690e+18],
          [-1.5263e+18, -2.2733e+18, -2.6230e+18, -2.0611e+18, -1.0381e+18]]],


        [[[-9.2933e+17, -2.7750e+18, -5.4230e+18, -6.5029e+18, -5.4308e+18],
          [-1.2915e+18, -3.7205e+18, -6.4145e+18, -7.1343e+18, -5.4902e+18],
          [-1.8585e+18, -4.6481e+18, -6.9502e+18, -7.3836e+18, -4.9507e+18],
          [-2.6654e+18, -5.2889e+18, -7.2654e+18, -7.1221e+18, -4.1085e+18],
          [-3.3320e+18, -5.5944e+18, -7.2323e+18, -6.3961e+18, -3.3587e+18]]],


        [[[-9.8040e+17, -2.7212e+18, -4.1524e+18, -4.3911e+18, -3.4494e+18],
          [-1.4418e+18, -3.4686e+18, -4.7175e+18, -4.7189e+18, -3.3046e+18],
          [-2.0829e+18, -4.0144e+18, -5.0422e+18, -4.7137e+18, -2.86

tensor([-4.2683e-01,  8.3729e-04,  3.2935e-02, -2.5290e-02,  1.9596e-02,
         5.3898e-03,  3.4771e-02, -1.1897e-02, -5.1886e-02, -1.4027e-02,
        -4.2634e-01, -4.4589e-02, -2.1014e-01, -3.1583e-02, -2.6102e-01,
        -4.5565e+02, -1.8365e-02, -3.0246e-02,  2.3190e-02,  1.5771e-02,
        -5.8955e-01, -1.9753e-02, -2.6786e-02, -7.1462e-02,  1.1758e-02,
        -6.5092e-02, -3.7670e-03,  3.3735e-02,  3.1774e-02, -4.8732e-02,
        -2.0239e-03, -3.1573e-01, -7.9073e-02,  2.6501e-02, -2.9357e-01,
         6.8474e-03, -1.1945e-01, -7.9032e-05,  8.8703e-03, -2.0933e-02,
        -2.3151e+03, -2.3202e-02,  1.5523e-02, -8.5146e-03, -7.1305e-01,
         3.8500e-04, -1.1368e-01, -1.0986e-02, -2.0234e-02, -2.2035e-01,
         2.2956e-02,  2.5241e-02, -3.8065e-02, -2.0782e+02, -2.0399e-02,
        -6.6659e-02, -2.4646e-02, -1.1578e+01, -3.1422e-02,  3.5103e-02,
        -5.8387e-03, -2.6071e-02,  1.8946e-02, -5.1527e+03, -5.9543e-02,
         4.8837e-03, -1.2943e-02, -1.6176e-02,  1.4

        -1.0140e+06, -2.8975e-02, -2.1624e-01, -4.2032e-02, -3.1900e-02,
        -5.6113e-02, -3.0085e-02, -1.7669e-02, -1.7541e-01, -2.2716e-01,
        -2.8230e-02,  5.8389e-01, -8.0080e-03, -3.6321e-02, -5.1931e-02,
         7.0031e-02, -2.0643e-02, -2.8231e-03, -1.4155e-02, -2.8291e-03,
         5.2745e-02, -3.3085e-02, -1.9049e-01, -3.1474e-02, -1.7399e-02,
        -4.8593e-02, -7.8428e-02, -8.9077e-03,  7.4009e-03, -2.1041e-01,
        -3.2352e-02, -2.8923e-01, -6.3481e-02,  3.3390e+01, -3.5009e-02,
        -6.6933e-02,  1.5998e-02,  1.7850e-02,  2.8532e+01,  2.7739e+02,
        -2.1994e-02, -3.2780e-02,  1.7106e+02, -4.1462e+01, -1.3276e-02,
        -4.5462e-02, -4.8859e-02, -2.0366e-02, -8.7191e-03, -3.1117e-02,
        -1.2114e-01, -1.6531e-02, -2.7560e-02, -2.9773e-02, -1.5493e-02,
        -4.2229e-01, -1.8805e-02, -7.8481e-02,  2.1333e-02, -6.7325e-02,
        -9.5089e+01, -4.4710e-02,  6.3506e-03, -3.7396e-02, -1.3888e-02,
        -3.0859e-01, -1.4325e-02, -1.4739e-01,  1.6

tensor([[[[-4.6855e-02, -3.7878e-02, -1.8922e+01, -9.0257e+01, -2.3545e+02],
          [-3.3474e-02, -1.7376e-01, -2.4350e+02, -3.4260e+02, -3.0570e+02],
          [ 4.3284e-03, -1.2956e+02, -5.5272e+02, -3.3589e+02, -5.2512e+01],
          [-1.3278e+00, -5.6190e+02, -5.2816e+02, -7.2151e+01, -7.3485e-02],
          [-4.0914e+02, -7.9349e+02, -3.6087e+02, -8.6140e+00, -4.2477e-02]],

         [[-1.8092e-01, -2.3478e-01, -4.5315e+01, -2.1757e+02, -5.6803e+02],
          [-1.7931e-01, -3.8586e-01, -5.8748e+02, -8.2826e+02, -7.3988e+02],
          [-1.8250e-01, -3.1152e+02, -1.3364e+03, -8.1465e+02, -1.2781e+02],
          [-2.5292e+00, -1.3580e+03, -1.2788e+03, -1.7597e+02, -3.0456e-01],
          [-9.8853e+02, -1.9194e+03, -8.7505e+02, -2.1326e+01, -4.4366e-02]],

         [[-1.7623e-01, -1.7114e-01, -3.6021e+01, -1.6810e+02, -4.3703e+02],
          [-1.6065e-01, -9.6433e-01, -4.5295e+02, -6.3370e+02, -5.6413e+02],
          [-4.7539e-02, -2.4302e+02, -1.0223e+03, -6.1641e+02, -9.5499e+

tensor([[[[-4.0160e+17, -1.2777e+18, -2.1015e+18, -2.2980e+18, -1.8661e+18],
          [-6.1512e+17, -1.6932e+18, -2.4207e+18, -2.4902e+18, -1.8208e+18],
          [-9.0612e+17, -2.0266e+18, -2.5919e+18, -2.5351e+18, -1.5786e+18],
          [-1.2980e+18, -2.1900e+18, -2.6846e+18, -2.3595e+18, -1.2690e+18],
          [-1.5263e+18, -2.2733e+18, -2.6230e+18, -2.0611e+18, -1.0381e+18]]],


        [[[-9.2933e+17, -2.7750e+18, -5.4230e+18, -6.5029e+18, -5.4308e+18],
          [-1.2915e+18, -3.7205e+18, -6.4145e+18, -7.1343e+18, -5.4902e+18],
          [-1.8585e+18, -4.6481e+18, -6.9502e+18, -7.3836e+18, -4.9507e+18],
          [-2.6654e+18, -5.2889e+18, -7.2654e+18, -7.1221e+18, -4.1085e+18],
          [-3.3320e+18, -5.5944e+18, -7.2323e+18, -6.3961e+18, -3.3587e+18]]],


        [[[-9.8040e+17, -2.7212e+18, -4.1524e+18, -4.3911e+18, -3.4494e+18],
          [-1.4418e+18, -3.4686e+18, -4.7175e+18, -4.7189e+18, -3.3046e+18],
          [-2.0829e+18, -4.0144e+18, -5.0422e+18, -4.7137e+18, -2.86

tensor([[-4.2908e-01, -1.1263e+01, -3.4906e+01,  ..., -8.1557e-01,
         -8.7575e-01, -1.6856e-01],
        [-3.7317e-02, -3.0162e-02, -3.9975e-02,  ..., -9.0611e-02,
         -1.4220e-01, -1.1659e-01],
        [ 4.7618e-03, -1.2189e-02, -3.5219e-02,  ..., -1.0890e-01,
         -1.2288e-01, -4.3031e-02],
        ...,
        [-2.8623e-02, -4.7503e-01, -1.2785e+01,  ..., -2.4783e+00,
         -2.7449e+00, -1.1592e+00],
        [-2.4633e-01, -4.4844e+00, -1.7416e-01,  ..., -1.2536e+00,
         -1.3745e+00, -5.7242e-01],
        [-2.2098e-02,  2.5889e-02, -2.1721e-02,  ..., -1.0220e+03,
         -4.2550e-03, -7.5653e+02]])
tensor([-4.2683e-01, -6.3882e-03,  2.9059e-02, -2.5290e-02,  5.7772e-03,
        -5.0840e-03, -1.3242e-01, -1.1897e-02, -5.1886e-02, -1.4027e-02,
        -4.2634e-01, -4.4589e-02, -2.1014e-01, -3.1583e-02, -2.6102e-01,
        -4.5565e+02, -1.8365e-02, -3.0246e-02,  1.2098e-01,  2.9046e-02,
        -5.8955e-01, -1.9753e-02, -2.6786e-02, -7.1462e-02, -3.9714e-01,
   


Test set: Average loss: 6.0936, Accuracy: 1028/10000 (10%)

tensor([[[[-4.0160e+17, -1.2777e+18, -2.1015e+18, -2.2980e+18, -1.8661e+18],
          [-6.1512e+17, -1.6932e+18, -2.4207e+18, -2.4902e+18, -1.8208e+18],
          [-9.0612e+17, -2.0266e+18, -2.5919e+18, -2.5351e+18, -1.5786e+18],
          [-1.2980e+18, -2.1900e+18, -2.6846e+18, -2.3595e+18, -1.2690e+18],
          [-1.5263e+18, -2.2733e+18, -2.6230e+18, -2.0611e+18, -1.0381e+18]]],


        [[[-9.2933e+17, -2.7750e+18, -5.4230e+18, -6.5029e+18, -5.4308e+18],
          [-1.2915e+18, -3.7205e+18, -6.4145e+18, -7.1343e+18, -5.4902e+18],
          [-1.8585e+18, -4.6481e+18, -6.9502e+18, -7.3836e+18, -4.9507e+18],
          [-2.6654e+18, -5.2889e+18, -7.2654e+18, -7.1221e+18, -4.1085e+18],
          [-3.3320e+18, -5.5944e+18, -7.2323e+18, -6.3961e+18, -3.3587e+18]]],


        [[[-9.8040e+17, -2.7212e+18, -4.1524e+18, -4.3911e+18, -3.4494e+18],
          [-1.4418e+18, -3.4686e+18, -4.7175e+18, -4.7189e+18, -3.3046e+18],
       

tensor([[[[-4.0160e+17, -1.2777e+18, -2.1015e+18, -2.2980e+18, -1.8661e+18],
          [-6.1512e+17, -1.6932e+18, -2.4207e+18, -2.4902e+18, -1.8208e+18],
          [-9.0612e+17, -2.0266e+18, -2.5919e+18, -2.5351e+18, -1.5786e+18],
          [-1.2980e+18, -2.1900e+18, -2.6846e+18, -2.3595e+18, -1.2690e+18],
          [-1.5263e+18, -2.2733e+18, -2.6230e+18, -2.0611e+18, -1.0381e+18]]],


        [[[-9.2933e+17, -2.7750e+18, -5.4230e+18, -6.5029e+18, -5.4308e+18],
          [-1.2915e+18, -3.7205e+18, -6.4145e+18, -7.1343e+18, -5.4902e+18],
          [-1.8585e+18, -4.6481e+18, -6.9502e+18, -7.3836e+18, -4.9507e+18],
          [-2.6654e+18, -5.2889e+18, -7.2654e+18, -7.1221e+18, -4.1085e+18],
          [-3.3320e+18, -5.5944e+18, -7.2323e+18, -6.3961e+18, -3.3587e+18]]],


        [[[-9.8040e+17, -2.7212e+18, -4.1524e+18, -4.3911e+18, -3.4494e+18],
          [-1.4418e+18, -3.4686e+18, -4.7175e+18, -4.7189e+18, -3.3046e+18],
          [-2.0829e+18, -4.0144e+18, -5.0422e+18, -4.7137e+18, -2.86

tensor([[[[-4.6855e-02, -3.7878e-02, -1.8922e+01, -9.0257e+01, -2.3545e+02],
          [-3.3474e-02, -1.7376e-01, -2.4350e+02, -3.4260e+02, -3.0570e+02],
          [ 4.3284e-03, -1.2956e+02, -5.5272e+02, -3.3589e+02, -5.2512e+01],
          [-1.3278e+00, -5.6190e+02, -5.2816e+02, -7.2151e+01, -7.3485e-02],
          [-4.0914e+02, -7.9349e+02, -3.6087e+02, -8.6140e+00, -4.2477e-02]],

         [[-1.8092e-01, -2.3478e-01, -4.5315e+01, -2.1757e+02, -5.6803e+02],
          [-1.7931e-01, -3.8586e-01, -5.8748e+02, -8.2826e+02, -7.3988e+02],
          [-1.8250e-01, -3.1152e+02, -1.3364e+03, -8.1465e+02, -1.2781e+02],
          [-2.5292e+00, -1.3580e+03, -1.2788e+03, -1.7597e+02, -3.0456e-01],
          [-9.8853e+02, -1.9194e+03, -8.7505e+02, -2.1326e+01, -4.4366e-02]],

         [[-1.7623e-01, -1.7114e-01, -3.6021e+01, -1.6810e+02, -4.3703e+02],
          [-1.6065e-01, -9.6433e-01, -4.5295e+02, -6.3370e+02, -5.6413e+02],
          [-4.7539e-02, -2.4302e+02, -1.0223e+03, -6.1641e+02, -9.5499e+

tensor([[[[-4.0160e+17, -1.2777e+18, -2.1015e+18, -2.2980e+18, -1.8661e+18],
          [-6.1512e+17, -1.6932e+18, -2.4207e+18, -2.4902e+18, -1.8208e+18],
          [-9.0612e+17, -2.0266e+18, -2.5919e+18, -2.5351e+18, -1.5786e+18],
          [-1.2980e+18, -2.1900e+18, -2.6846e+18, -2.3595e+18, -1.2690e+18],
          [-1.5263e+18, -2.2733e+18, -2.6230e+18, -2.0611e+18, -1.0381e+18]]],


        [[[-9.2933e+17, -2.7750e+18, -5.4230e+18, -6.5029e+18, -5.4308e+18],
          [-1.2915e+18, -3.7205e+18, -6.4145e+18, -7.1343e+18, -5.4902e+18],
          [-1.8585e+18, -4.6481e+18, -6.9502e+18, -7.3836e+18, -4.9507e+18],
          [-2.6654e+18, -5.2889e+18, -7.2654e+18, -7.1221e+18, -4.1085e+18],
          [-3.3320e+18, -5.5944e+18, -7.2323e+18, -6.3961e+18, -3.3587e+18]]],


        [[[-9.8040e+17, -2.7212e+18, -4.1524e+18, -4.3911e+18, -3.4494e+18],
          [-1.4418e+18, -3.4686e+18, -4.7175e+18, -4.7189e+18, -3.3046e+18],
          [-2.0829e+18, -4.0144e+18, -5.0422e+18, -4.7137e+18, -2.86

tensor([-4.2683e-01, -6.3882e-03,  2.6814e-02, -2.5290e-02,  3.2343e-02,
        -5.0840e-03, -1.3242e-01, -1.1897e-02, -5.1886e-02, -1.4027e-02,
        -4.2634e-01, -4.4589e-02, -2.1014e-01, -3.1583e-02, -2.6102e-01,
        -4.5565e+02, -1.8365e-02, -3.0246e-02,  6.4526e-02, -4.7488e-01,
        -5.8955e-01, -1.9753e-02, -2.6786e-02, -7.1462e-02, -3.9714e-01,
        -6.5092e-02, -3.7670e-03,  5.6332e-03, -1.2231e+02, -4.8732e-02,
        -2.0239e-03, -3.1573e-01, -7.9073e-02, -2.6624e-01, -2.9357e-01,
        -5.8852e-01, -1.1945e-01, -7.9032e-05, -1.1607e-01, -2.0933e-02,
        -2.3151e+03, -2.3202e-02,  5.8147e-02, -8.5146e-03, -7.1305e-01,
        -3.4804e-02, -1.1368e-01, -1.0986e-02, -2.0234e-02, -2.2035e-01,
        -1.9468e+05, -5.2940e+02, -3.8065e-02, -2.0782e+02, -2.0399e-02,
        -6.6659e-02, -2.4646e-02, -1.1578e+01, -3.1422e-02, -4.6853e-01,
        -5.8387e-03, -2.6071e-02,  3.0051e-02, -5.1527e+03, -5.9543e-02,
        -2.7567e-02, -1.2943e-02, -1.6176e-02, -3.9

In [21]:
a = (1,2,3)
print(*a)

1 2 3


In [17]:
import torch
a = torch.randn(10)
b = torch.randn(10)
print(a + b)


tensor([-1.1955,  0.7454,  2.2958,  0.7627, -1.8554,  2.1034,  0.9754, -0.5315,
        -1.4054, -0.4366])


In [13]:
c = a * b
print(c)
c[c < 0] = 0
print(c)
print(sum(c) / c.numel())

tensor([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.])
tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 0.])
tensor(0.4000)


In [19]:
import torch
a = torch.randn(10, 10)
print(a)
b= sum(sum(a))
print(b < 1)
print(torch.sum(a))

tensor([[ 0.2005, -1.4676, -0.1612,  1.0327,  0.6711, -0.5866,  0.1845,  0.7546,
          0.7648,  0.0665],
        [-1.1616, -1.2742,  0.5208,  0.0455,  1.3800, -1.3549, -1.2841,  0.4271,
         -1.0102,  0.7728],
        [ 1.2919, -0.0172,  1.9121,  0.6939, -0.0478,  0.2780, -0.0511,  0.8210,
          1.6182, -1.4080],
        [-1.4707,  0.3174, -0.1436,  0.7356,  0.0676, -1.3979, -0.2142, -1.4966,
         -0.5186, -1.0357],
        [-0.2476, -0.6345,  0.9889,  0.3647,  0.2549, -0.1785,  1.2954,  0.7947,
         -0.5517, -2.0726],
        [-0.3288, -1.4315,  1.1696,  0.2306, -2.1533,  1.0698,  0.3071,  0.1144,
          0.1599, -1.0269],
        [ 1.2161,  1.2372,  0.8799, -0.4821, -0.8188, -0.0562, -1.7864,  2.1884,
         -2.4226,  0.8561],
        [-1.1335,  0.6174,  0.7172, -1.3658,  1.8122, -1.0729, -0.4403, -0.5271,
         -0.7175,  0.4633],
        [ 1.3391, -0.1014,  0.8842,  0.3893,  1.4606,  1.7285, -1.0272, -0.4547,
          2.2184, -1.1150],
        [-1.9452,  

In [2]:
a = [1,2,3]
b = [4,5,6]

for x in a:
    for y in b:
        break
    print(x, y)

1 4
2 4
3 4
